# Generated by Django 3.0.8 on 2020-07-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsbase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basa',
            name='drivable',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
