# Generated by Django 3.0.8 on 2020-07-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsbase', '0002_basa_drivable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basa',
            name='manufacturer',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='basa',
            name='model',
            field=models.CharField(max_length=20),
        ),
    ]
